## 2. 1. 1 Library Import

In [1]:
import numpy as np

In [2]:
from numpy import random

## 2. 1. 2. magic Command

In [3]:
# magic command 전체 리스트 확인하기
%quickref

# 2.2 넘파이

In [4]:
import numpy as np

In [5]:
%precision 3

'%.3f'

## 2.2.2. 배열 생성과 조작, 가공

In [6]:
# 배열
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [7]:
# 데이터 형
data.dtype

dtype('int32')

In [8]:
# dimension
print('차원수: ', data.ndim)
print('원소수: ', data.size)

차원수:  1
원소수:  10


In [9]:
# calculation
print(data * 2)
print('곱셈', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) * np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))
print('거듭제곱', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) ** 2)
print('나눗셈', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) / np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

[18  4  6  8 20 12 14 16  2 10]
곱셈 [10 18 24 28 30 30 28 24 18 10]
거듭제곱 [  1   4   9  16  25  36  49  64  81 100]
나눗셈 [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


In [10]:
# sort
print('현재 순서대로: ', data)
data.sort()
print('정렬 후: ', data)
data[::-1].sort()
print('역정렬 후: ', data)

현재 순서대로:  [ 9  2  3  4 10  6  7  8  1  5]
정렬 후:  [ 1  2  3  4  5  6  7  8  9 10]
역정렬 후:  [10  9  8  7  6  5  4  3  2  1]


In [11]:
# 통계값
print('Min: ', data.min())
print('Max: ', data.max())
print('Sum: ', data.sum())
print('Cum: ', data.cumsum())
print('Ratio: ', data.cumsum() / data.sum())

Min:  1
Max:  10
Sum:  55
Cum:  [10 19 27 34 40 45 49 52 54 55]
Ratio:  [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


## 2.2.3 난수

In [12]:
# 난수
import numpy.random as random

In [13]:
random.seed(0)
rnd_data = random.rand(10)
print('10개의 난수 배열: ', rnd_data)
print('복원 추출: ', random.choice(data, 10))
print('비복원 추출: ', random.choice(data, 10, replace = False))

10개의 난수 배열:  [0.549 0.715 0.603 0.545 0.424 0.646 0.438 0.892 0.964 0.383]
복원 추출:  [4 3 3 2 9 5 1 2 1 6]
비복원 추출:  [ 6  9  4  3  8  2  5  1 10  7]


- random.seed(): 괄호 안의 숫자를 0 이상의 정수를 넣으면 고정, 비워두면 비고정, 음수 혹은 소수점 아래를 넣으면 에러
- %timeit np.sum(원하는 변수): 그 변수를 계산하는데 걸린 시간을 알 수 있다

## 2. 2. 4. 행렬

In [14]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
array1 = np.arange(9).reshape(3, 3)
print(array1, "\n")
print("첫 번째 행", array1[0,:], "\n")
print("첫 번째 열", array1[:,0])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

첫 번째 행 [0 1 2] 

첫 번째 열 [0 3 6]


In [16]:
# 행렬 연산
array2 = np.arange(9, 18).reshape(3,3)
print(array2, "\n")
print("행렬 곱셈", np.dot(array1, array2), "\n")
print("행렬 각 원소 간 곱", array1 * array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]] 

행렬 곱셈 [[ 42  45  48]
 [150 162 174]
 [258 279 300]] 

행렬 각 원소 간 곱 [[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [17]:
# 원소가 0 혹은 1인 행렬
print(np.zeros((2,3), dtype = np.int64), "\n")
print(np.ones((2,3), dtype = np.float64))

[[0 0 0]
 [0 0 0]] 

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# 연습문제 2-1
array1 = np.arange(1, 51)
print(array1)
sum_array = np.sum(array1)
print("1부터 50까지 다 더한 값: ", sum_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
1부터 50까지 다 더한 값:  1275


In [19]:
# 연습문제 2-2
rnd_array = random.rand(10)
print(rnd_array)
print('Min: ', rnd_array.min())
print('Max: ', rnd_array.max())
print('Sum: ', rnd_array.sum())

[0.461 0.781 0.118 0.64  0.143 0.945 0.522 0.415 0.265 0.774]
Min:  0.11827442586893322
Max:  0.9446689170495839
Sum:  5.063525753473914


In [20]:
# 연습문제 2-3
array3 = (np.ones((5, 5), dtype = np.float64)) * 3
print("행렬: ", array3, "\n")
print("행렬의 제곱: ", np.dot(array3, array3))

행렬:  [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]] 

행렬의 제곱:  [[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]


# 2. 3. Scipy

In [21]:
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar

## 2. 3. 2. 행렬연산

In [22]:
matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])
print('행렬식: ', linalg.det(matrix))
print('역행렬: \n', linalg.inv(matrix))
print('\n')
eig_value, eig_vector = linalg.eig(matrix)
print('고윳값: ', eig_value)
print('고유벡터: \n', eig_vector)

행렬식:  -4.0
역행렬: 
 [[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


고윳값:  [-1.+0.j  2.+0.j  2.+0.j]
고유벡터: 
 [[ 0.577  0.816  0.408]
 [ 0.577 -0.408 -0.816]
 [ 0.577 -0.408  0.408]]


## 2. 3. 3. 뉴턴법

In [23]:
# 방정식 해 구하기
def my_function(x):
    return (x ** 2 + 2 * x + 1)

In [24]:
from scipy.optimize import newton
print(newton(my_function, 0))

-0.9999999852953906


In [25]:
# 최솟값 구하기
print(minimize_scalar(my_function, method = 'Brent'))

     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002


In [26]:
def my_function(x):
    return (x ** 4)
print("뉴턴법 해", newton(my_function, 0))
print('최솟값  구하기 \n', minimize_scalar(my_function, method = 'Brent'))

뉴턴법 해 0.0
최솟값  구하기 
      fun: 0.0
    nfev: 36
     nit: 32
 success: True
       x: 0.0


- 최솟값 구하기는, 아래로 볼록한 모양의 함수에서만 가능하다. 그럼 구간을 정해서 최솟값 찾는 거는 어떻게 할 수 있는가?

In [27]:
# 연습문제 2-4
A = np.array([[1, 2, 3], [1, 3, 2], [3, 1, 2]])
print(A)
print("행렬식", linalg.det(A))

[[1 2 3]
 [1 3 2]
 [3 1 2]]
행렬식 -12.0


In [28]:
# 연습문제 2-5
print("역행렬", linalg.inv(A))
eig_value, eig_vector = linalg.eig(A)
print("고윳값: ", eig_value)
print("고유벡터 \n", eig_vector)

역행렬 [[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
고윳값:  [ 6.   +0.j -1.414+0.j  1.414+0.j]
고유벡터 
 [[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]


In [29]:
# 연습문제 2-6
def function_a(x):
    return(x ** 3 + 2*x + 1)
print(newton(function_a, 0))

-0.45339765151640365


# 2.4 판다스 기초

In [30]:
import pandas as pd
from pandas import Series, DataFrame

## 2. 4. 2. Series 사용법

In [31]:
sample_pandas_data = pd.Series([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
print(sample_pandas_data)

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64


In [32]:
sample_pandas_data = pd.Series([0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
                              index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(sample_pandas_data)

a     0
b    10
c    20
d    30
e    40
f    50
g    60
h    70
i    80
j    90
dtype: int64


In [33]:
print("데이터 값: ", sample_pandas_data.values)
print("인덱스 값: ", sample_pandas_data.index)

데이터 값:  [ 0 10 20 30 40 50 60 70 80 90]
인덱스 값:  Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')


## 2. 4. 3. DataFrame 사용법

In [34]:
attri_data1 = {'ID': ['100', '101', '102', '103', '104'],
               'City': ['Seoul', 'Pusan', 'Daegu', 'Gangneung', 'Seoul'],
               'Birth_year': [1900, 1989, 1992, 1997, 1982],
               'Name': ['Junho', 'Heejin', 'Mijung', 'Minho', 'Steve']}
attri_data_frame1 = DataFrame(attri_data1)
print(attri_data_frame1)

    ID       City  Birth_year    Name
0  100      Seoul        1900   Junho
1  101      Pusan        1989  Heejin
2  102      Daegu        1992  Mijung
3  103  Gangneung        1997   Minho
4  104      Seoul        1982   Steve


In [35]:
attri_data_frame_index1 = DataFrame(attri_data1, index = ['a', 'b', 'c', 'd', 'e'])
print(attri_data_frame_index1)

    ID       City  Birth_year    Name
a  100      Seoul        1900   Junho
b  101      Pusan        1989  Heejin
c  102      Daegu        1992  Mijung
d  103  Gangneung        1997   Minho
e  104      Seoul        1982   Steve


In [36]:
# 주피터 환경에서 데이터 출력
attri_data_frame_index1

ID       City  Birth_year    Name
a  100      Seoul        1900   Junho
b  101      Pusan        1989  Heejin
c  102      Daegu        1992  Mijung
d  103  Gangneung        1997   Minho
e  104      Seoul        1982   Steve

## 2. 4. 4. 행렬 다루기

In [37]:
# 전치
attri_data_frame1.T

0       1       2          3      4
ID            100     101     102        103    104
City        Seoul   Pusan   Daegu  Gangneung  Seoul
Birth_year   1900    1989    1992       1997   1982
Name        Junho  Heejin  Mijung      Minho  Steve

In [38]:
# 특정 열 추출 (한 줄)
attri_data_frame1.Birth_year

0    1900
1    1989
2    1992
3    1997
4    1982
Name: Birth_year, dtype: int64

In [39]:
# 특정 열 추출 (복수 줄)
attri_data_frame1[['ID', 'Birth_year']]

ID  Birth_year
0  100        1900
1  101        1989
2  102        1992
3  103        1997
4  104        1982

## 2. 4. 5. 데이터 추출

In [40]:
attri_data_frame1[attri_data_frame1['City'] == 'Seoul']

ID   City  Birth_year   Name
0  100  Seoul        1900  Junho
4  104  Seoul        1982  Steve

In [41]:
attri_data_frame1['City'] == 'Seoul'

0     True
1    False
2    False
3    False
4     True
Name: City, dtype: bool

In [42]:
attri_data_frame1[attri_data_frame1['City'].isin(['Seoul', 'Pusan'])]

ID   City  Birth_year    Name
0  100  Seoul        1900   Junho
1  101  Pusan        1989  Heejin
4  104  Seoul        1982   Steve

In [43]:
attri_data_frame1[attri_data_frame1['Birth_year'] < 1990]

ID   City  Birth_year    Name
0  100  Seoul        1900   Junho
1  101  Pusan        1989  Heejin
4  104  Seoul        1982   Steve

## 2. 4. 6. 데이터 삭제와 결합