# 5. 1. 개요와 사전준비

## 5. 1. 2. 라이브러리 임포트

In [1]:
# 필요한 라이브러리 임포트
import numpy as np
import numpy.random as random
import scipy as sp

# 시각화 라이브러리
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

# 소수점 세 번째 자리까지 표시
%precision 3

'%.3f'

# 5. 2. 넘파이를 이용한 계산 방법

## 5. 2. 1. 인덱스 참조

In [2]:
sample_array = np.arange(10)

# 원본 데이터
print('sample_array: ', sample_array)

# 앞에서 숫자 5개를 추출해 sample_array_slice에 저장(슴라이싱)
sample_array_slice = sample_array[0:5]
print('sample_array_slice: ', sample_array_slice)

# sample_array_slice 처음 3개 원소를 10으로 변경
sample_array_slice[0:3] = 10
print('변경한 sample_array_slice: ', sample_array_slice)

# 슬라이싱은 원본 리스트의 원소 값도 변경한다는 점에 주의
print('변경 후 sample_array: ', sample_array)

# 데이터 복사
print('\n데이터 복사')

# copy하고 다른 object를 생성
sample_array_copy = np.copy(sample_array)
print('sample_array_copy: ', sample_array_copy)

sample_array_copy[0:3] = 20
print('변경한 sample_array_copy: ', sample_array_copy)

# 원본 리스트의 원소는 변경되지 않음
print('sample_array: ', sample_array)

sample_array:  [0 1 2 3 4 5 6 7 8 9]
sample_array_slice:  [0 1 2 3 4]
변경한 sample_array_slice:  [10 10 10  3  4]
변경 후 sample_array:  [10 10 10  3  4  5  6  7  8  9]

데이터 복사
sample_array_copy:  [10 10 10  3  4  5  6  7  8  9]
변경한 sample_array_copy:  [20 20 20  3  4  5  6  7  8  9]
sample_array:  [10 10 10  3  4  5  6  7  8  9]


In [3]:
# 불 인덱스 참조

# 데이터 생성
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
print('\n')
random.seed(0)
data = random.randn(5, 5)

print(sample_names)
print(data)

print('\n')

print('불값 출력', sample_names == 'a')
print('\n')
print('불 인덱스 참조\n', data[sample_names == 'a'])
print('\n')



['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


불값 출력 [ True False False False  True]


불 인덱스 참조
 [[ 1.764  0.4    0.979  2.241  1.868]
 [-2.553  0.654  0.864 -0.742  2.27 ]]




In [4]:
# 조건 제어
# 조건을 제어하기 위해 불 배열 생성
cond_data = np.array([True, True, False, False, True])

# 배열 x_array 생성
x_array = np.array([1,2,3,4,5])

# 배열 y_array 생성
y_array = np.array([100,200,300,400,500])

# 조건 제어 실행
print(np.where(cond_data, x_array, y_array))

[  1   2 300 400   5]


In [5]:
# 연습문제 5-1
# 불 인덱스를 이용해 b에 해당하는 데이터를 추출하시오
# 데이터 생성
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
print('\n')
random.seed(0)
data = random.randn(5, 5)

print(sample_names)
print(data)

print('\n')

print('b 불 인덱스 참조\n', data[sample_names == 'b'])



['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


b 불 인덱스 참조
 [[-0.977  0.95  -0.151 -0.103  0.411]]


In [6]:
# 연습문제 5-2

print('c 빼고 불 인덱스 참조\n', data[sample_names != 'c'])

c 빼고 불 인덱스 참조
 [[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [7]:
# 연습문제 5-3
# x: 3,4 , y: 1,2,5

x_array = np.array([1, 2, 3, 4, 5])
y_array = np.array([6, 7, 8, 9, 10])

cond_data = np.array([True, True, False, False, True])
print(np.where(cond_data, y_array, x_array))

[ 6  7  3  4 10]


## 5. 2. 2. 넘파이를 이용한 연산 작업

In [8]:
# 중복 삭제

cond_data = np.array([True, True, False, False, True])

# cond_data를 출력
print(cond_data)

# 중복 원소 삭제
print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [9]:
# 범용함수
sample_data = np.arange(10)
print('원본 데이터: ', sample_data)
print('모든 원소의 제곱근: ', np.sqrt(sample_data))
print('모든 원소의 자연상수 지수함수: ', np.exp(sample_data))

원본 데이터:  [0 1 2 3 4 5 6 7 8 9]
모든 원소의 제곱근:  [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
모든 원소의 자연상수 지수함수:  [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [10]:
# 최소, 최대 ,평균, 합계 계산

# arange로 9개의 원소를 갖는 배열을 생성하고 reshape로 3*3 행렬로 재배열
sample_multi_array_data1 = np.arange(9).reshape(3,3)

print(sample_multi_array_data1)
print('\n')
print('최솟값: ', sample_multi_array_data1.min())
print('최댓값: ', sample_multi_array_data1.max())
print('평균: ', sample_multi_array_data1.mean())
print('합계: ', sample_multi_array_data1.sum())
print('\n')

# 행렬을 지정해 합계를 구함
print('행 합계: ', sample_multi_array_data1.sum(axis = 1))
print('열 합계: ', sample_multi_array_data1.sum(axis = 0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


최솟값:  0
최댓값:  8
평균:  4.0
합계:  36


행 합계:  [ 3 12 21]
열 합계:  [ 9 12 15]


In [11]:
# 진릿값 판정

# 진릿값 판정 배열함수
cond_data = np.array([True, True, False, False, True])

print('True가 적어도 하나라도 있는가? ', cond_data.any())
print('모두 True인가? ', cond_data.all())
print('\n')

sample_multi_array_data1 = np.arange(9).reshape(3, 3)
print(sample_multi_array_data1)
print('5보다 큰 숫자가 몇 개인가? ', (sample_multi_array_data1 > 5).sum())

True가 적어도 하나라도 있는가?  True
모두 True인가?  False


[[0 1 2]
 [3 4 5]
 [6 7 8]]
5보다 큰 숫자가 몇 개인가?  3


In [12]:
# 대각성분 계산

# 행렬 연산
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('대각성분: ', np.diag(sample_multi_array_data1))
print('대각성분의 합: ', np.trace(sample_multi_array_data1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
대각성분:  [0 4 8]
대각성분의 합:  12


In [13]:
# 연습문제 5-4
# 다음 데이터에 대해 모든 원소의 제곱근 행렬을 출력하세요

sample_multi_array_data2 = np.arange(16).reshape(4,4)
print(sample_multi_array_data2)
print('\n')

print('모든 원소의 제곱근 행렬\n', np.sqrt(sample_multi_array_data2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


모든 원소의 제곱근 행렬
 [[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


In [14]:
# 연습문제 5-5
print('\n')
print('최솟값: ', sample_multi_array_data2.min())
print('최댓값: ', sample_multi_array_data2.max())
print('합계: ', sample_multi_array_data2.sum())
print('평균: ', sample_multi_array_data2.mean())
print('\n')



최솟값:  0
최댓값:  15
합계:  120
평균:  7.5




In [15]:
# 연습문제 5-6
print('대각성분의 합: ', np.trace(sample_multi_array_data2))

대각성분의 합:  30


## 5. 2. 3. 배열의 조작과 브로드캐스트

In [16]:
# 재배열

# 데이터 생성
sample_array = np.arange(10)
print(sample_array)
print('\n')

# 재배열
sample_array2 = sample_array.reshape(2,5)
print(sample_array2)
print('\n')

sample_array3 = sample_array.reshape(5,2)
print(sample_array3)

[0 1 2 3 4 5 6 7 8 9]


[[0 1 2 3 4]
 [5 6 7 8 9]]


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
# 데이터 결합

# 수직 방향 결합

# 데이터 생성
sample_array3 = np.array([[1, 2, 3], [4, 5, 6]])
sample_array4 = np.array([[7, 8, 9], [10, 11, 12]])
print(sample_array3)
print('\n')
print(sample_array4)

# 수직 방향으로 결합, 파라미터 axis에 0 지정
np.concatenate([sample_array3, sample_array4], axis = 0)

[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
# vstack을 이용한 수직 방향 결합
np.vstack((sample_array3, sample_array4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
# 수평 방향으로 결합, 파라미터 axis에 1 지정
np.concatenate([sample_array3, sample_array4], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [20]:
# hstack을 이용한 수직 방향 결합
np.hstack((sample_array3, sample_array4))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
# 배열 분할

# 데이터 생성
sample_array3 = np.array([[1, 2, 3], [4, 5, 6]])
sample_array4 = np.array([[7, 8, 9], [10, 11, 12]])
sample_array_vstack = np.vstack((sample_array3, sample_array4))

# 생성한 데이터 sample_array_vstack 출력
sample_array_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# 5. 3. 사이파이 응용

## 5. 3. 1. 보간법

In [22]:
# x는 linspace를 이용해 0에서 10까지 11개의 원소를 갖는 등차수열
x = np.linsplace(1, 10, num = 11, endpoint = True)

# y값 생성
y = np.cos(x, y, )

AttributeError: module 'numpy' has no attribute 'linsplace'

In [23]:
from scipy import linalg

A = np.identity(5)
A[0, :] = 1
A[:, 0] = 1
A[0, 0] = 5
b = np.ones(5)

# 정방행렬을 LU 분해함
(LU, piv) = sp.linalg.lu_factor(A)
L = np.identity(5) + np.tril(LU, -1)
U = np.triu(LU)
P = np.identity(5)[piv]

# 해를 구함
x = sp.linalg.lu_solve((LU, piv), b)
x

array([-3.,  4.,  4.,  4.,  4.])

In [24]:
help(np.tril)

Help on function tril in module numpy:

tril(m, k=0)
    Lower triangle of an array.
    
    Return a copy of an array with elements above the `k`-th diagonal zeroed.
    
    Parameters
    ----------
    m : array_like, shape (M, N)
        Input array.
    k : int, optional
        Diagonal above which to zero elements.  `k = 0` (the default) is the
        main diagonal, `k < 0` is below it and `k > 0` is above.
    
    Returns
    -------
    tril : ndarray, shape (M, N)
        Lower triangle of `m`, of same shape and data-type as `m`.
    
    See Also
    --------
    triu : same thing, only for the upper triangle
    
    Examples
    --------
    >>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 0,  0,  0],
           [ 4,  0,  0],
           [ 7,  8,  0],
           [10, 11, 12]])



In [25]:
help(np.conj)

Help on ufunc object:

conjugate = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate a

In [30]:
from scipy import integrate
sp.integrate.quad(lambda x: 4/(1+x**2), 1, 5)

(2.352, 0.000)