In [1]:
import numpy as np

In [2]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data[::-1].sort()
data

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [3]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data[::-2].sort()
data

array([ 9,  8,  3,  6, 10,  5,  7,  4,  1,  2])

In [4]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data[::-3].sort()
data

array([ 9,  2,  3,  7, 10,  6,  5,  8,  1,  4])

In [5]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data[::-4].sort()
data

array([ 9,  6,  3,  4, 10,  5,  7,  8,  1,  2])

In [6]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data[::-5].sort()
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [7]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data[::-6].sort()
data

array([ 9,  2,  3,  5, 10,  6,  7,  8,  1,  4])

In [8]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[::1].sort()
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[::2].sort()
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[::3].sort()
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[::4].sort()
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[::5].sort()
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[::6].sort()
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
data[::3]

array([ 1,  4,  7, 10])

In [15]:
np.sort(data)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
data = np.array([0,1,2,3,4,5,6,7,8,9])
data[1:6:2].sort()
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
data = np.array([0,1,2,3,4,5,6,7,8,9])
data[1:6:-2].sort()
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
data = np.array([9, 2, 3, 6, 10, 4, 7, 8, 1, 5])
data[1:6:2].sort()
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [19]:
data[1:6:2]

array([2, 4, 6])

In [20]:
data = np.array([9, 2, 3, 6, 10, 4, 7, 8, 1, 5])
data[1:6:-2].sort()
data

array([ 9,  2,  3,  6, 10,  4,  7,  8,  1,  5])

In [21]:
data = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
data[1:6:2].sort()
data

array([10,  5,  8,  7,  6,  9,  4,  3,  2,  1])

In [22]:
data = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
data[1:6:2]

array([9, 7, 5])

In [23]:
data = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
data[1:6:-2]

array([], dtype=int32)

In [24]:
data = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
data[1:6:-2].sort()
data

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [25]:
data = np.array(['b', 'e', 'a', 'i' ,'c', 'f', 'j', 'g', 'd', 'h'])
data[::1].sort()
data

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [26]:
data = np.array(['b', 'e', 'a', 'i' ,'c', 'f', 'j', 'g', 'd', 'h'])
data[::-1].sort()
data

array(['j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'], dtype='<U1')

In [27]:
data = np.array(['b', 'e', 'a', 'i' ,'c', 'f', 'j', 'g', 'd', 'h'])
data[::-2].sort()
data

array(['b', 'i', 'a', 'h', 'c', 'g', 'j', 'f', 'd', 'e'], dtype='<U1')